//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticInformation
    {
        public int ID { get; set; }
        public int FirstParameter { get; set; }
        public int SecondParameter { get; set; }
        public string Operation { get; set; }
        public Nullable<int> Result { get; set; }
        public string MessageInfo { get; set; }
        public System.DateTime CreatedTimeStamp { get; set; }
    }
}
